### ISSUE TITLE
cabal failure

### ISSUE THREAD

**Issue by JoePython1** [chrisdone/emacs-haskell-config#11]
While running 
cabal install packages/structured-haskell-mode/

I got the following error message.
Registering cpphs-1.19.2...
Installed cpphs-1.19.2
Downloading haskell-src-exts-1.15.0.1...
[1 of 1] Compiling Main             ( /tmp/haskell-src-exts-1.15.0.1-22192/haskell-src-exts-1.15.0.1/Setup.hs, /tmp/haskell-src-exts-1.15.0.1-22192/haskell-src-exts-1.15.0.1/dist/setup/Main.o )
Linking /tmp/haskell-src-exts-1.15.0.1-22192/haskell-src-exts-1.15.0.1/dist/setup/setup ...
Configuring haskell-src-exts-1.15.0.1...
setup: The program happy version >=1.17 is required but it could not be found.
Failed to install haskell-src-exts-1.15.0.1
cabal: Error: some packages failed to install:
haskell-src-exts-1.15.0.1 failed during the configure step. The exception was:
ExitFailure 1
structured-haskell-mode-1.0.4 depends on haskell-src-exts-1.15.0.1 which
failed to install.

**Comment by chrisdone** [comment]
I think a `cabal install happy` might be required ahead of installing `haskell-src-exts` (cabal doesn't track such dependencies).
