### ISSUE TITLE
How to combine this with Stackage exclusive?

### ISSUE THREAD

**Issue by cies** [chrisdone/emacs-haskell-config#2]
Stackage exclusive misses some of the dependencies, and some of the dependencies. Namely: ghci-ng, hindent, haskell-doc and SHM. Now I now these are shipped as sub-repos, but still those sub-repos done compile on a recent stackage-excl.

Here my findings (x-post from the reddit thread)...

SHM needs haskell-src-exts 1.15 (while 1.16 is in stackage-excl):

    % cabal install packages/structured-haskell-mode/                  
    Warning: The package list for 'stackage' is 19 days old.
    Run 'cabal update' to get the latest list of available packages.
    Resolving dependencies...
    Configuring structured-haskell-mode-1.0.4...
    Building structured-haskell-mode-1.0.4...
    Failed to install structured-haskell-mode-1.0.4
    Last 10 lines of the build log ( /home/cies/.cabal/logs/structured-haskell-mode-1.0.4.log ):
    structured-haskell-mode-1.0.4...
    [1 of 1] Compiling Main             ( src/Main.hs, dist/build/structured-haskell-mode/structured-haskell-mode-tmp/Main.p_o )

    src/Main.hs:143:21:
        Not in scope: data constructor ‘IHead’
        Perhaps you meant ‘DHead’ (imported from Language.Haskell.Exts.Annotated)

    src/Main.hs:144:21:
        Not in scope: data constructor ‘IHead’
        Perhaps you meant ‘DHead’ (imported from Language.Haskell.Exts.Annotated)

`ghci-ng` also misses some things (did not look much into this one, as I did not understand the p_dyn error):

    % cabal install packages/ghci-ng       
    Warning: The package list for 'stackage' is 19 days old.
    Run 'cabal update' to get the latest list of available packages.
    Resolving dependencies...
    Configuring ghci-ng-7.8.3...
    Building ghci-ng-7.8.3...
    Failed to install ghci-ng-7.8.3
    Last 10 lines of the build log ( /home/cies/.cabal/logs/ghci-ng-7.8.3.log ):

    ghc/Main.hs:66:8:
        Could not find module ‘Data.List’
        Perhaps you haven't installed the "p_dyn" libraries for package ‘base’?
        Use -v to see a list of the files searched for.

    ghc/Main.hs:67:8:
        Could not find module ‘Data.Maybe’
        Perhaps you haven't installed the "p_dyn" libraries for package ‘base’?
        Use -v to see a list of the files searched for.

`haskell-docs` has issues compiling on Stackage as well:

    % cabal install packages/haskell-docs/
    Warning: The package list for 'stackage' is 19 days old.
    Run 'cabal update' to get the latest list of available packages.
    Resolving dependencies...
    cabal: Could not resolve dependencies:
    trying: haskell-docs-4.2.2 (user goal)
    next goal: haddock (dependency of haskell-docs-4.2.2)
    Dependency tree exhaustively searched.

So only `hindent` compiled out of the box on a "recent" Stackage snapshot.

Somehow I expect you are using Stackage yourself too... So how do you do it? I can think of some options:

* some kind of sandboxing (cabal-1.20 allows package repos to be set per sandbox)
* stackage-incl
* self installing all dependencies

Frankly I dont know the best way to tackle this; and I really want to tackle this, as my current Emacs setup is very sub-optimal.

Thanks in advance.

**Comment by cies** [comment]
I moved on from exclusive: yay for LTS Haskell and `cabal.config`s!

No longer an issue for me, so I close it...

**Comment by chrisdone** [comment]
\o/
